env = HYPRCURSOR_SIZE,24
env = HYPRCURSOR_THEME, Moga-neon-blue
env = XCURSOR_SIZE,24
env = XCURSOR_THEME, Moga-neon-blue
env = GTK_THEME, Tokyonight-Dark-Storm

exec-once = hyprctl setcursor Moga-neon-blue 20