-- Variáveis de Ambiente (Cursores e Temas)
hl.env("HYPRCURSOR_SIZE", "20")
hl.env("HYPRCURSOR_THEME", "Moga-Candy-Macchiato")
hl.env("XCURSOR_SIZE", "20")
hl.env("XCURSOR_THEME", "Moga-Candy-Macchiato")
hl.env("GTK_THEME", "Tokyonight-Dark-Storm")

-- Execução na Inicialização (Autostart)
hl.on("hyprland.start", function ()
    hl.exec_cmd("hyprctl setcursor Moga-Candy-Macchiato 20")
end)