-- Variáveis de Ambiente (Cursores e Temas)
hl.env("HYPRCURSOR_SIZE", "20")
hl.env("HYPRCURSOR_THEME", "Moga-Sandy")
hl.env("XCURSOR_SIZE", "20")
hl.env("XCURSOR_THEME", "Moga-Sandy")
hl.env("GTK_THEME", "Kanagawa")

-- Execução na Inicialização (Autostart)
hl.on("hyprland.start", function ()
    hl.exec_cmd("hyprctl setcursor Moga-Sandy 20")
end)