-- Variáveis de Ambiente (Cursores e Temas)
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_THEME", "Moga-Candy-Grey")
hl.env("XCURSOR_SIZE", "24")
hl.env("XCURSOR_THEME", "Moga-Candy-Grey")
hl.env("GTK_THEME", "Gruvbox-Dark-Medium")

-- Execução na Inicialização (Autostart)
hl.on("hyprland.start", function ()
    hl.exec_cmd("hyprctl setcursor Moga-Candy-Grey 24")
end)